---
output:
    html_document:
        toc: yes
params:
    title: 'Neil1'
    working_folder: '/Users/cowfox/Desktop/_rna_lib_analysis/__analysis/2018_12_10-ML_Random_Forest-Tuning'
    
    # Dataset "codenames" - Use "comma" to sparate
    # Possible datasets - neil1_experimental, neil1_degenerate_computational, ttyh2_ecs_bc_experimental, ttyh2_bc_degenerate_computational, HEK293.WT1, Hela_no_gRNA, Hela_no_gRNA+IFN, u87_ctrl_vs_kd
    dataset_codename_str: 'neil1_computational'

    # Use "comma" to sparate
    feature_column_str: 'mut_exist, site_struct, site_length, site_prev_nt, site_next_nt, site_prev_struct, site_next_struct, u_count, u_all_stem_length, u_hairpin_length, u1_struct, u1_length, u1_distance, u2_struct, u2_length, u2_distance, d_count, d_all_stem_length, d1_struct, d1_length, d1_distance, d2_struct, d2_length, d2_distance'

# 
title: "ML Feature Coorelation - `r params$title`"
---

```{r "knitr config", cache = FALSE, include=FALSE}
require("knitr")
# 
script_folder_path = getwd()
if (params$working_folder != '') {
    # Set it "globally"
    opts_knit$set(root.dir = params$working_folder)
}

# Global Chunk Options
# Ref - https://yihui.name/knitr/options/
opts_chunk$set(
    echo = TRUE
)
```

```{r Info, include=FALSE}
# ## Purpose of This Script
# It aims to run "Random Forest" on the RNA Liv data. 
# 
# ## Tutorial of Rmarkdown
# - https://bookdown.org/yihui/rmarkdown/
```

```{r Libraries, include=FALSE}
#
library(knitr)

# Random Forest
library(mlbench)
library(caret)
library(randomForest)
library(gbm)

# Plot
library(gplots)
library(ggplot2)
library(Hmisc)
library(corrplot)

library(doMC)  # Multi-core

# Tools
library(onehot)
library(rlist)
library(gtools)
library(gsubfn)
library(GetoptLong) # String interpolation - https://cran.r-project.org/web/packages/GetoptLong/vignettes/variable_interpolation.html
```

```{r Setup, include=FALSE}
# Clear - NO NEED. It needs "passing params"
# rm(list=ls())

# Global options
options(warn=-1)

# Use multi-core
registerDoMC(cores=8)

# Local scripts
source(normalizePath(file.path(script_folder_path, './utils.R')))
source(normalizePath(file.path(script_folder_path, './helper.R')))
```

```{r Prep, include=FALSE}
# Set the "Seed" for following "Random Forest" running
seed_num = 166
set.seed(seed_num)

#
feature_columns = c()
if (params$feature_column_str != '') {
    feature_columns = str_to_list(params$feature_column_str)
}
```

# Summary

This script helps check the "correlation" of ML features. 

## Feature List

The following features are considered: 

```{r Feature list, echo=FALSE}

# 
for (feature_name in feature_columns) {
    #
    print(qq("- @{feature_name}"))
}

```

# Datasets Pre-processing

The following dataset are checked in this script. 

```{r  List datasets - training & validation, echo=FALSE }

# Build the list of "dataset codenames"
dataset_meta = c()
if (params$dataset_codename_str != '') {
    dataset_meta = str_to_list(params$dataset_codename_str)
}

# 
for (dataset_codename in dataset_meta) {
    #
    print(qq("- @{dataset_codename}"))
}

```

```{r Load datasets, echo=FALSE}

# Temp fix
# - Use `setwd()` tp set the "working folder" since `opts_knit$set(root.dir = params$working_folder)` not working.
# - Ignore "warning" in this chunk
if (params$working_folder != '') {
    setwd(params$working_folder)
}

# Loop into "codenames" and build the "dataset variables"
for (dataset_codename in dataset_meta) {
    # file path
    file_path = qq("./_output/feature_matrices/@{dataset_codename}.features.csv")
    assign(qq("feature_file_relative_path.@{dataset_codename}"), file_path)
    
    # original data
    data_orig = read.csv(file=file_path, header=TRUE, sep=",")
    assign(qq("data_orig.@{dataset_codename}"), data_orig)
}

```


```{r Pre-processing, echo=FALSE}

for (dataset_codename in dataset_meta) {
    #
    dataset.name = qq("data_orig.@{dataset_codename}")
    dataset = get(dataset.name)
    
    #
    # Filtered via "feature list"
    if (length(feature_columns) > 0) {
        dataset <- dataset[ , (names(dataset) %in% feature_columns)]
    }
    
    # Drop any colum that is all "NA"
    dataset <- dataset[, colSums(is.na(dataset)) < nrow(dataset)]
    # Try to fix any "missing value" via "imputation"
    dataset <- na.roughfix(dataset)
    # Remove any columns with "zero" variance 
    remove_cols <- nearZeroVar(dataset, names = TRUE,
                               freqCut = 2, uniqueCut = 0.0001)
    all_cols <- names(dataset)
    dataset <- dataset[ , setdiff(all_cols, remove_cols)]
    
    # Save
    dataset.filtered.name = qq("dataset.filtered.@{dataset_codename}")
    assign(dataset.filtered.name, dataset)
}
```

```{r Process, echo=FALSE}

for (dataset_codename in dataset_meta) {
    # 
    dataset.name = qq("dataset.filtered.@{dataset_codename}")
    dataset = get(dataset.name)
    
    print(qq("Summary - @{dataset_codename}:"))
    print(summary(dataset))
    
    # 
    # Convert it to "one-hot" format
    encoder = onehot(dataset)
    onehot <- predict(encoder, dataset)
    
    print(qq("One-hot - @{dataset_codename}:"))
    print(summary(onehot))

    # Save
    dataset.onehot.name = qq("dataset.one_hot.@{dataset_codename}")
    assign(dataset.filtered.name, onehot)
}
```

# Correlation - Spearman's Rank-order

```{r "Spearman's rank-order correlation", fig.width=16, fig.height=16, echo=FALSE, warning=FALSE, dev=c('png', 'pdf')}

# Temp fix
# - Use `setwd()` tp set the "working folder" since `opts_knit$set(root.dir = params$working_folder)` not working.
# - Ignore "warning" in this chunk
if (params$working_folder != '') {
    setwd(params$working_folder)
}

columns_to_plot = c(
    # "site_prev_struct=H", "u1_struct=H", "d2_struct=S", "d1_struct=I", "site_struct=S", "site_next_struct=I"
    )

for (dataset_codename in dataset_meta) {
    # 
    dataset.name = qq("dataset.one_hot.@{dataset_codename}")
    dataset.onehot = get(dataset.name)
    
    # filter
    dataset.onehot = as.data.frame(dataset.onehot)
    if (length(columns_to_plot) > 0) {
        dataset.onehot <- dataset.onehot[ , (names(dataset.onehot) %in% columns_to_plot)]
    } else {
        # Print the "column headers"
        print(names(dataset.onehot))
    }
    
    # 
    cor.spearman <- rcorr(as.matrix(dataset.onehot), type=c("spearman"))
    
    # Corelation Plot
    # svg(qq("corr_spearman_@{dataset_codename}.svg"),
    #     height=16, width=16)
    plot.corrplot <- corrplot(cor.spearman$r, 
             type = "upper",  # display upper triangular of the correlation matrix
             order = "hclust", # hierarchical clustering order, 
             
             # The significance test
             p.mat = cor.spearman$P, 
             sig.level = 0.01, # Significance level
             insig = "blank", # If show indicator for "no significant coefficient"
             # insig = "p-value", # Show "p-values"
             
             # 
             tl.col = "black", tl.srt = 45, tl.cex = 0.8,
             
             # 
             title = qq("Correlation of Features (Spearman) - @{dataset_codename}"),
             mar=c(0, 0, 1, 0)
             )
    # dev.off()
    
    # Heatmap
    # svg(qq("heatmap_corr_spearman_@{dataset_codename}.svg"), 
    #     height=16, width=16)
    col<- colorRampPalette(c('#67001f','#b2182b','#d6604d','#f4a582','#fddbc7','#d1e5f0','#92c5de','#4393c3','#2166ac','#053061'))(100)
    plot.heatmap <- heatmap.2(as.matrix(cor.spearman$r),
            col = col,
            Rowv = TRUE,
            Colv = TRUE,
            scale = "none",
            trace = "none",
            margins = c(20, 20),
            
            # Col
            cexCol = 0.8,
            srtCol = 315, adjCol = c(0, 1),
            
            # Row
            cexRow = 1,
            
            # Title
            main = qq("Correlation of Features (Spearman) - @{dataset_codename}")
          )
    # dev.off()
}

```

# Correlation - Pearson

```{r "Pearson correlation", fig.width=16, fig.height=16, echo=FALSE, warning=FALSE, dev=c('png', 'pdf')}

# Temp fix
# - Use `setwd()` tp set the "working folder" since `opts_knit$set(root.dir = params$working_folder)` not working.
# - Ignore "warning" in this chunk
if (params$working_folder != '') {
    setwd(params$working_folder)
}

for (dataset_codename in dataset_meta) {
    # 
    dataset.name = qq("dataset.one_hot.@{dataset_codename}")
    dataset.onehot = get(dataset.name)
    
    # filter
    dataset.onehot = as.data.frame(dataset.onehot)
    if (length(columns_to_plot) > 0) {
        dataset.onehot <- dataset.onehot[ , (names(dataset.onehot) %in% columns_to_plot)]
    } else {
        # Print the "column headers"
        print(names(dataset.onehot))
    }
    
    # 
    cor.spearman <- rcorr(as.matrix(dataset.onehot), type=c("pearson"))
    
    # Corelation Plot
    # svg(qq("corr_pearson_@{dataset_codename}.svg"),
    #     height=16, width=16)
    plot.corrplot <- corrplot(cor.spearman$r, 
             type = "upper",  # display upper triangular of the correlation matrix
             order = "hclust", # hierarchical clustering order, 
             
             # The significance test
             p.mat = cor.spearman$P, 
             sig.level = 0.01, # Significance level
             insig = "blank", # If show indicator for "no significant coefficient"
             # insig = "p-value", # Show "p-values"
             
             # 
             tl.col = "black", tl.srt = 45, tl.cex = 0.8,
             
             # 
             title = qq("Correlation of Features (Pearson) - @{dataset_codename}"),
             mar=c(0, 0, 1, 0)
             )
    # dev.off()
    
    # Heatmap
    # svg(qq("heatmap_corr_pearson_@{dataset_codename}.svg"), 
    #     height=16, width=16)
    col<- colorRampPalette(c('#67001f','#b2182b','#d6604d','#f4a582','#fddbc7','#d1e5f0','#92c5de','#4393c3','#2166ac','#053061'))(100)
    plot.heatmap <- heatmap.2(as.matrix(cor.spearman$r),
            col = col,
            Rowv = TRUE,
            Colv = TRUE,
            scale = "none",
            trace = "none",
            margins = c(20, 20),
            
            # Col
            cexCol = 0.8,
            srtCol = 315, adjCol = c(0, 1),
            
            # Row
            cexRow = 1,
            
            # Title
            main = qq("Correlation of Features (Pearson) - @{dataset_codename}")
          )
    # dev.off()
}

```



