## ===============================================================================
#  Logging Configs 
#
## ===============================================================================

version: 1

#
disable_existing_loggers: False

## --------------------------------------------------------------------------------
#  Formatters
formatters:
    simple:
        format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
    verbose:
        format: "[%(levelname)s] %(asctime)s - %(pathname)s:%(lineno)d\n%(message)s"
    debug:
        format: "[%(levelname)s] %(asctime)s - %(pathname)s:%(lineno)d\n\033[34m%(message)s\033[0m"
    error:
        format: "Component: %(module)s\nErrorCode: %(funcName)s\nReason: %(funcName)s\nDetail: [%(message)s]"

## --------------------------------------------------------------------------------
#  Handlers
handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: verbose
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: verbose
        filename: ./script-info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: ./script-error.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

## --------------------------------------------------------------------------------
#  Loggers
loggers:
    neo_rna.script:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]
        propagate: no

root:
    level: INFO
    handlers: [console, info_file_handler, error_file_handler]