---
output:
    html_document:
        toc: yes
params:
    title: 'Neil'
    working_folder: '/Users/cowfox/Desktop/_rna_lib_analysis/__analysis/2019_01_10-Sequence_Logo'
    
    # Data Source
    # dataset_source: '/Users/cowfox/Desktop/_rna_lib_analysis/__rna_library/_structure_summary/TTYH2_BC-rna_lib-structure_summary-indel_fixed.csv'
    dataset_source: '/Users/cowfox/Desktop/_rna_lib_analysis/__rna_library/_structure_summary/TTYH2_Combined-rna_lib-structure_summary-indel_fixed.csv'
    
    # Editing Value Threshold
    editing_value_min: 0.3
    editing_value_max: NA
    
    # Sequence "Range" around "Editing Site"
    sequence_range: 10

# 
title: "Sequence Logo Chart - `r params$title`"
---

```{r "knitr config", cache = FALSE, include=FALSE}
require("knitr")
# 
script_folder_path = getwd()
if (params$working_folder != '') {
    # Set it "globally"
    opts_knit$set(root.dir = params$working_folder)
}

# Global Chunk Options
# Ref - https://yihui.name/knitr/options/
opts_chunk$set(
    echo = TRUE
)
```

```{r Info, include=FALSE}
# ## Purpose of This Script
# It loads the "structure annotation type" info around "editing site" (in "#" of nt) and generate "sequence logo" chart.  
# 
# ## Tutorial of Rmarkdown
# - https://bookdown.org/yihui/rmarkdown/
```

```{r Libraries, include=FALSE}
#
library(knitr)

# Plot
library(RColorBrewer)
library(ggplot2)
library(ggseqlogo) # https://omarwagih.github.io/ggseqlogo/
# EDLogo 
# - https://github.com/kkdey/Logolas 
# - https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2489-3
library(Logolas)
library(REBayes)

# 
library(doMC)  # Multi-core

# Tools
library(rlist)
library(gtools)
library(gsubfn)
library(GetoptLong) # String interpolation
```

```{r Setup, include=FALSE}
# Clear - NO NEED. It needs "passing params"
# rm(list=ls())

# Global options
options(warn=-1)

# Use multi-core
registerDoMC(cores=8)

# Local scripts
# source(normalizePath(file.path(script_folder_path, './utils.R')))
# source(normalizePath(file.path(script_folder_path, './helper.R')))
```


# Summary

It loads the "structure annotation type" info around "editing site" (in "#" of nt) and generate "sequence logo" chart.  

```{r "Base Info", echo=FALSE}

# 
print(GetoptLong::qq("- Data Source: @{params$title}"))
# print(GetoptLong::qq("- Editing Value Threshold - MIN: @{params$editing_value_min}"))
# print(GetoptLong::qq("- Editing Value Threshold - MAX: @{params$editing_value_max}"))
print(paste0("- Editing Value Threshold - MIN: ", params$editing_value_min))
print(paste0("- Editing Value Threshold - MAX: ", params$editing_value_max))
print(GetoptLong::qq('- Sequence Range around Editing Site: @{params$sequence_range}'))

```


```{r "Load Data", echo=FALSE}

# 
data_orig = read.csv(file=params$dataset_source, header=TRUE, sep=",", stringsAsFactors=FALSE)

# 
data_orig$A.to.I_editing_level <- suppressWarnings(as.numeric(as.character(data_orig$A.to.I_editing_level)))
data_orig = data_orig[ is.na(data_orig$A.to.I_editing_level)==FALSE, ]
data_orig$A.to.I_editing_site <- suppressWarnings(as.integer(as.character(data_orig$A.to.I_editing_site)))

# Exam the Distribution of the "editing level"
ggplot() + 
    aes(data_orig$A.to.I_editing_level) + 
    geom_histogram(binwidth = 0.01, colour = "black", fill = "white")
```

```{r Process, echo=FALSE}

# Filter the data based on "threshold"
if (!is.na(params$editing_value_min)) {
    data.filter = data_orig[ data_orig$A.to.I_editing_level >= params$editing_value_min, ]
}
if (!is.na(params$editing_value_max)) {
    data.filter = data_orig[ data_orig$A.to.I_editing_level <= params$editing_value_max, ]
}

# 
annotation_filter_func <- function(df) {
    editing_site <- as.integer(df[3])
    computational_annotation <- df[8]
    
    # print(editing_site)
    # print(computational_annotation)
    start = editing_site - params$sequence_range
    end = editing_site + params$sequence_range
    filtered = substr(computational_annotation, start, end)
    
    #
    return(filtered)
}

data.filter$computational_dot_bracket_annotation_filtered = apply(data.filter, 1, annotation_filter_func)
```

# Normal Sequence Logo Chart

```{r Plot - Logo, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8, fig.height=6}

# 
# Ref - https://omarwagih.github.io/ggseqlogo/
# ggseqlogo(data.filter$computational_dot_bracket_annotation_filtered)
# plot <- ggplot() +
#     geom_logo(data.filter$computational_dot_bracket_annotation_filtered, stack_width = 1) +
#     theme_logo() +
#     theme(
#         legend.position="none"
#         ) +
#     # ggtitle(qq('Editing Level Range: @{params$editing_value_min} - @{params$editing_value_max}')) +
#     ggtitle(paste0("Editing Level Range: ", params$editing_value_min, " - ", params$editing_value_max)) +
#     xlab(qq('nt (Editing Site: @{params$sequence_range + 1})'))
# plot

# Ignore console output
suppressWarnings(logomaker(data.filter$computational_dot_bracket_annotation_filtered, 
          type = "Logo", 
          # bg = bg,
          # color_type = "per_row",
          # colors = brewer.pal(n = 11, name = "Spectral"),
          # color_seed = 2000,
          logo_control = list(
              frame_width = 1,
              
              # 
              pop_name = paste0("Editing Level Range: ", params$editing_value_min, " - ", params$editing_value_max),
              xlab = GetoptLong::qq('position (Editing Site: @{params$sequence_range + 1})'),
              ylab = "Enrichment Score"
          )
    ))
```

# ED Sequence Logo Chart

```{r Plot - EDLogo, echo=FALSE, warning=FALSE, message=FALSE, fig.width=8, fig.height=6}

suppressWarnings(logomaker(data.filter$computational_dot_bracket_annotation_filtered, 
          type = "EDLogo", 
          # color_type = "per_row",
          # colors = brewer.pal(n = 11, name = "Spectral"),
          # color_seed = 2000,
          logo_control = list(
              frame_width = 1,
              
              # 
              pop_name = paste0("Editing Level Range: ", params$editing_value_min, " - ", params$editing_value_max),
              xlab = GetoptLong::qq('position (Editing Site: @{params$sequence_range + 1})'),
              ylab = "Enrichment Score"
          )
))
```